name: your-env-name
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - torch=2.2.2
  - matplotlib=3.10.1
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - tqdm=4.67.1
  - pip:
    - asttokens==3.0.0
    - fsspec==2025.3.0
    - joblib==1.4.2
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - nest-asyncio==1.6.0
    - pyzmq==24.0.1
    - scikit-learn==1.6.1
    - sympy==1.13.3
